### ISSUE TITLE
Prime 4

### ISSUE THREAD

**Issue by VeeJayLizard** [jochenunger/vdj-denon-prime-skin#4]
Hi Jochen.
Have problems with your skin.
1. Have crash while switching to daylight mode
2. No browser is shown in 2 deck vertical mode
Regards Tomas.
Please can you give me your email address for better communication?
Thank you.

tomascerny@hotmail.com

**Comment by jochenunger** [comment]
Thx for your feedback and nice to have you here. Can you give more information on:

- Operating System
- Engine DJ Version

Regarding 1.: Does it happen, when you switch to daylight using the default desktop skin? If yes, does it happen, when you disconnect your controller and switch?
![image](https://user-images.githubusercontent.com/61796494/223804215-69f83a6c-f409-43f1-acd9-8fb9a46990a9.png)

Regarding 2.: Are you using grid view in the normal browser window, too?
![image](https://user-images.githubusercontent.com/61796494/223804619-33f3345e-cbf1-42a6-a38b-329472ac92b4.png)

**Comment by VeeJayLizard** [comment]
Latest on 0.2.0
MacOS ventura
No grid view used, tried both with and without grid view on.
regards Tomas

**Comment by VeeJayLizard** [comment]
daylight mode was switched on my Prime 4 when this happen

**Comment by jochenunger** [comment]
Hey Tomas,
I was playing around with the daylight mode in several situations. I was not able to crash it. Except, when the main skin (the desktop skin) of VDJ was not able to handle it. Could you please use the default VDJ Desktop skin with my controller skin and verify, if this crashes still?

**Comment by VeeJayLizard** [comment]
Crash was while using Vanced skin. Could not reproduce now.

Odesláno z iPhonu

9. 3. 2023 v 17:14, Jochen Unger ***@***.***>:

﻿

Hey Tomas,
I was playing around with the daylight mode in several situations. I was not able to crash it. Except, when the main skin (the desktop skin) of VDJ was not able to handle it. Could you please use the default VDJ Desktop skin with my controller skin and verify, if this crashes still?

**Comment by jochenunger** [comment]
Regarding the 2 Deck Vertical problem: Do you use the skin with a high fps rendering. Higher then 30fps?
If so, try to reduce it to 30fps and check the browser again:
![image](https://user-images.githubusercontent.com/61796494/224343184-d43814f5-0e41-480c-91f4-88e81d55873c.png)

**Comment by VeeJayLizard** [comment]
Hi Jochen,
tried that, but still no browser view on 2deck vertical mode.
Regards Tomas.

Odesláno z iPhonu

10. 3. 2023 v 15:36, Jochen Unger ***@***.***>:

﻿

Regarding the 2 Deck Vertical problem: Do you use the skin with a high fps rendering. Higher then 30fps?
If so, try to reduce it to 30fps and check the browser again:
[image]<https://user-images.githubusercontent.com/61796494/224343184-d43814f5-0e41-480c-91f4-88e81d55873c.png>
